name: "BUG 汇报"
description: "软件运行过程中报错或者出现了不该有的东西……"
labels: [BUG]
assignees:
  - tangge233
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请**逐个检查**下列项目，并勾选确认。"
    options:
    - label: "我已经在 ISSUE 中搜索过并确定**没有重复的反馈**"
      required: true
    - label: "我已确定问题出现在**最新版本**的 DR 工具箱"
      required: true
    - label: "我已确定问题具有**可复现性（即可以通过固定操作触发）**"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "描述清楚如何发生的以及操作步骤。"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 错误报告、日志与附件
    description: "请提供环境信息：DR工具箱 → 日志 → 导出信息"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
  validations:
    required: true
