blank_issues_enabled: false
contact_links:
  - name: 提问
    url: https://github.com/tangge233/DreaRobotToolBox/discussions/categories/%E6%B1%82%E5%8A%A9%E9%97%AE%E7%AD%94%E5%8C%BA
    about: 我不想提交反馈，只是想问一些问题
  - name: 新功能提议或投票
    url: https://github.com/tangge233/DreaRobotToolBox/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8
    about: 为新功能投票或者发起一个关于新功能的投票
